###############################################################################
# Empire V
#
# @file    ../Commodities/Makefile
# @version 1.0 - Initial implementation
#
# @author Mark Nelson <marknels@hawaii.edu>
# @date   29 Jan 2021
# @copyright (c) 2021 Mark Nelson
###############################################################################

TARGETS = Commodity.o
TESTS   = CommodityTest

all: $(TARGETS)

include ../Common.mk
