###############################################################################
# Empire ][
#
# @file    Server/Makefile
# @version 1.0 - Initial implementation
#
# @author Mark Nelson <marknels@hawaii.edu>
# @date   16 Mar 2021
# @copyright (c) 2021 Mark Nelson
###############################################################################

TARGETS = Core.o Log.o
TESTS   = CoreTest

all: $(TARGETS)

include ../Common.mk
